### ISSUE TITLE
Server crash every few hours 

### ISSUE THREAD

**Issue by EgalTv1** [AllTheMods/ATM-3#1000]
## Expected Behavior
the server Shouldn't crash

## Current Behavior
The server crashes every 2-3 hours or more often for no reason.

## Steps to Reproduce

1.
2.
3.
4.

## Log
Server log: https://gist.github.com/EgalTv1/0138c4b40033fb3adb3ca1bb480a9463
Crash log: https://gist.github.com/EgalTv1/d5e60db4921b20f2454ecc7faff559b8

## Detailed Description
Hey guys, my friends and I started All The Mods 3 a few weeks ago. In the beginning we had no problems, but since a few days the server crashes frequently and has only a tps of 10-13. we have already removed our melt and also our Draconic Energy core, but nothing works. the console also broadcasts every few seconds: Can't keep up! Did the system time change, or is the server overloaded?. We have a total of 12 GB Ram but the server is only using 6GB

Thanks for your help :)

**Comment by Pelotrio** [comment]
Your server is crashing because it forcefully shuts down due to too much lag. It would probably the easiest if you would join the atm discord server and then we can try to profile your server to find out why it is lagging so much. Just ask in the atm3 channel and I will try to to help you as best as I can. https://discord.gg/3paFjuRfz9
