### ISSUE TITLE
Suggestion: Cross-mod uses for TR Galena and Bauxite

### ISSUE THREAD

**Issue by djcosmic2** [AllTheMods/ATM-3#134]
I never use TechReborn, but I always hate having so much Galena and Bauxite in my sorting system with nothing to do with it.
I mean Bauxite is _kinda_ useable as it is ore dictionary with IE bauxite, and you can drop it into an ordictionificator to get aluminum, but they both just seem like a wasted resource to anyone who never goes into tech reborn.

Ideas could be using the dust in crafting recipes or making it somehow be smelted into other metals

**Comment by OrdinatorStouff** [comment]
aluminum is a specific thing I'd like to address, and wouldn't mind maybe making something minor to do with the galena as well.

**Comment by OrdinatorStouff** [comment]
This is no longer relevant as we've moved to IE bauxies/alumionum as the primary worldgen for aluminum.

There COULD be more to do with aluminum/bauxite etc but the issue was originally created becasue bauxite and galena ore were in worldgen (they are not now) and had excess resources from processing them
