### ISSUE TITLE
[1.12.2 ATM3 v4.2] Unable to make basic machine casing from IC2

### ISSUE THREAD

**Issue by Morpheus1101** [AllTheMods/ATM-3#212]
I've tried using iron plate as per JEI from every mod that lists an iron plate and without success, this essentially breaks the fundamental requirement to start IC2 since a good amount of its machiens require the machine casing.

**Comment by OrdinatorStouff** [comment]
I'll look into it but for the meantime can you see if you can make a TechReborn basic frame and then craft/convert into an IC2 frame in crafting grid?

**Comment by OrdinatorStouff** [comment]
A user on discord reported similar issues with recipes. They were using CreeperHost's server update not setting up files manually. After downloading a fresh profile and deleting and then copying over fresh scripts folder the issue was fixed for them. Can you confirm same steps? Manually/FTP delete then re-upload scripts folder from fresh client profile/download and report back?

**Comment by Morpheus1101** [comment]
Del and reapply of fresh scripts folder indeed solved the issue
