### ISSUE TITLE
Infinity Capacitor/Creative Cube Recipe weirdness

### ISSUE THREAD

**Issue by Beannsss** [AllTheMods/ATM-3#235]
I find the recipe for the infinity capacitor a little bit weird... I'm not sure that it makes sense for it to require the ATM star when you can just get a creative cube with the same thing. The ability to store a "infinite" RF is completely negated by the ability to generate "infinite" RF. Just a small suggestion, I think the recipe for the energy core is perfectly balanced enough for the capacitor.

**Comment by OrdinatorStouff** [comment]
I might need you to explain your reasoning in more detail, please. If I understand you're suggesting that the creative handheld capacitor should only need an energy core instead of an ATM Star but I don't think I fully understand what you mean for the reason why.

**Comment by ShadowsVengeance** [comment]
Sure, I am simply suggesting that the Infinity capacitor, from overloaded, the block that just lets you a large amount of energy (while generating none) should require only the energy core. I see why this could be confusing from the original post since "capacitor" is used for many different items/blocks in the game. The reasoning for this is that with the ATM star, you can simply craft a creative cube/capacitor from mekanism/draconic evolution and generate infinite energy which negates the need for storing it.

**Comment by ShadowsVengeance** [comment]
Store "Infinite" Energy:
![image](https://user-images.githubusercontent.com/8314499/31970099-ea6c7354-b8e4-11e7-8ad3-d7e56e32cfeb.png)

Generate "Infinite" Energy:
![image](https://user-images.githubusercontent.com/8314499/31970114-f8ddafca-b8e4-11e7-997f-902d3085d52c.png)

**Comment by Boomflex** [comment]
Currently works as intended up will look in to it in the future.

Thanks for the report though!
