### ISSUE TITLE
No Mystical Agriculture Seeddrop (Config is changed)

### ISSUE THREAD

**Issue by Darianna77** [AllTheMods/ATM-3#236]
Okay....i use Mystical Agriculture and have found out that there is NO additional Seeddrop. Have found the Config the drop chance ist on 0....have change it to the dafault from 10 
But the Pack seems to completely ignore this change or there is something broken then i cant get any seed drop

Whats happen? Anyone else have this problem?

**Comment by OrdinatorStouff** [comment]
Some modded farming are hardcoded to not drop any extra seeds. This is mostly because mystical agriculture plants are coded quite differently from "normal" crops.

If you plant a bunch Mystical Agriculture seed in normal vanilla farmland and harvest when mature you should see the extra seeds drop. I know for sure that both the IE Cloche and Industrial Foregoing harvester do not respect the extra drop config and there are likely many other mods that are the same.

The unique nature of Mystical Agriculture's code meant that in order for other mods to support the crops at all, some hard-coded amount of seed drop was necessary, so to play safe, many just default to "0"

**Comment by OrdinatorStouff** [comment]
not a pack issue (i.e working as intended)
