### ISSUE TITLE
Draconic Evolution Basic Crafting Injector Recipe not working

### ISSUE THREAD

**Issue by ajwalters95** [AllTheMods/ATM-3#237]
The recipe listed in JEI does not yield a Basic Crafting Injector from Draconic Evolution. 

The recipes work in single player. Only not working in multiplayer

Running version 4.2 and am playing on a server if that matters. Have tried in AE system and in vanilla crafting table. 

![2017-10-24_21 29 40](https://user-images.githubusercontent.com/13601149/31977563-1c893c28-b903-11e7-8618-3970e1210887.png)

**Comment by ajwalters95** [comment]
Same with fusion crafting core

![2017-10-25_07 27 34](https://user-images.githubusercontent.com/13601149/31998599-01b1e10e-b956-11e7-908c-54370c6363d4.png)

**Comment by ajwalters95** [comment]
And the Wyvern Energy Core. Draconic Evolution is unusable in this pack

![2017-10-25_07 43 35](https://user-images.githubusercontent.com/13601149/31999286-5bdc82b8-b958-11e7-9703-d127752f4a78.png)

**Comment by OrdinatorStouff** [comment]
Did you close the issue because you figured out what was wrong? I've played alongside dozens of players that have fusion crafting and draconic stuff.

I'm wondering if there's a mismatch between server and client configs, or possible the scripts -- they are not 1:1 then any number of annoyances can pop up, mostly dealing with recipes

![core](https://user-images.githubusercontent.com/6283913/32014517-23e1e32e-b973-11e7-80d8-40fb99af2eed.png)

**Comment by GreatBanoose** [comment]
Not sure if it's helpful, but I noticed tons of non working recipes on the server I play on when we were running 4.2, but the moment we upgraded to 4.3 all the issues with crafting recipes fixed themselves.   

Might be worth having your server upgrading to the most recent version of the pack to see if that helps.
