### ISSUE TITLE
Wrong oredict on some ingots with RS processing patterns

### ISSUE THREAD

**Issue by Gorden211** [AllTheMods/ATM-3#254]
I use ingots to pulverize them for the pulvers needed for Thermal Expansion higher tier materials such as signalum and enderium.
When making an RS pattern with oredict added making a Silver Ingot to Pulverized Silver, the items fed into the pulverizer are Invar instead of Silver. 
Similar instead of lead being pulverized the item being fed into the pulverizer is actually Bronze.  
Disabling oredict fixes the issue but is still really strange that enabling oredict has that kind of influence on the ingots.

**Comment by OrdinatorStouff** [comment]
Autocrafting patters are susceptable to bugs like this, especially when some mods change oredict or recipe registration in an update after the crafting patter was made. If the problem is still prevalant and reproduceable in pack version 5.6 please check the RS issue tracker for open/closed tickets about the same thing and see if there is discussion there.
