### ISSUE TITLE
[ATM 3 V5.1] Dimensions classed as no-oxygen planets

### ISSUE THREAD

**Issue by OsirisKalev** [AllTheMods/ATM-3#281]
Since the addition of Advanced Rocketry, all Abyssalcraft dimensions now require the usage of the space suit from Advanced Rocketry, along with Lost Cities, Twilight Forest and the inside of Compact Machines. Obviously, this is a little silly.

Tested in singleplayer and multiplayer.

Edit: After some tinkering with configs, I've fixed it by changing I:minDimension in advancedRocketry.cfg to 31 and changed the Abyssalcraft dimensions and Lost City from 30 to 26. However I assume you might have better numbers to set these to.

**Comment by OrdinatorStouff** [comment]
I'm going to close this out since there is little we can do on the pack side anymore.

Dim collisions should only be possible anymore with existing worlds that had created dims that AR expects to "own"

If there are still **non-dynamic** (i.e. rftools) dims without oxygen that aren't AR, please open a new ticket so we can tweak it in the AR config.
