### ISSUE TITLE
Game freezes when changing the language or resource pack

### ISSUE THREAD

**Issue by PapiDimmi** [AllTheMods/ATM-3#287]
All the Mods 3 version 5.1.

**Comment by OrdinatorStouff** [comment]
So this isn't an "answer" per-se but this is normal. Reloading resources in modpacks since 1.11 or even 1.10 have resulted in freezing/crashing/mixed-up texturemap, etc.  
  
I don't think it's "okay" but I also don't think there's anything that can be done on the modpack end as the issues are likely deep-rooted and quite low-priority (rebooting the client is all that's needed for the changes to have taken place and be fine).

I do appreciate taking the time to report it but for now we're not going to worry about trying to figure this out.

**Comment by PapiDimmi** [comment]
Just a note: It freezes, not crashes. If you wait a few minutes, you don’t need to restart your client.

**Comment by OrdinatorStouff** [comment]
Ahh well yeah that's basically like what the game is doing when you first are launching minecraft, a large percentage of that long startup time is processing all the sound/texture/model resources. When you change those in-game it has to re-load allll of them again and it can't do anything else until it's done. You can even experience this pause/delay in vanilla minecraft when adding/changing texture packs but it's not as long since there are far less total resources in vanilla vs a kitchen sink pack
