### ISSUE TITLE
Advanced Rocketry misconfigured

### ISSUE THREAD

**Issue by ouroborus** [AllTheMods/ATM-3#291]
Advanced Rocketry's Airtight Seal isn't showing up correctly. According to the [this issue](https://github.com/zmaster587/AdvancedRocketry/issues/911), it's a matter of changing the configuration.

![image](https://user-images.githubusercontent.com/392047/33207139-706cdfae-d0c1-11e7-906e-c4b734cf4405.png)

**Comment by ouroborus** [comment]
Seems that Advanced Rocketry as a whole hasn't been configured. Tried going to the moon and ended up in AE2's storage cell dimension.

**Comment by OsirisKalev** [comment]
Further iterating on this, changing the enchantment id does not fix the problem for an already generated world, only for new worlds.

**Comment by ouroborus** [comment]
@OsirisKalev Any idea how to fix the dimensions as well?

**Comment by ouroborus** [comment]
Here's what I did to fix things on my server:

1. Shutdown server and make a backup
2. Fix things
  - Deleted `world/advRocketry` (This is where AR's dimension and other data is stored are stored. Once this is created, original config files are ignored.)
  - Updated `config/advRocketry/advancedrocketry.config`
    - Changed biome IDs in `biome` section to the `500` range
    - Updated biome IDs in `planets` section to match biome ID changes. (These are mismatched already in the ATM3 distribution.)
    - Updated `I:spaceStationId` to `-500` to set space station dimension
  - Updated `config/advRocketry/planetdefs.xml` to change planet IDs (`DIMID`) to `-500` range
    - Earth ID isn't changed
    - Commented out extra entry for Magnis Vulpes.
3. Renamed advanced rocketry jar to prevent loading
4. Start server (do not log in)
5. `/fml confirm`
  - Some of the blocks and items are under libVulpes and won't be lost. The blocks may need to be dug up and re-placed as the AR multiblock information is lost.
  - Specific AR blocks will be lost.
  - All AR inventory items will be lost.
6. Stop server
7. Rename advanced rocketry jar so it will load.
8. Start server
9. Stop server
10. Edit `level.dat` to change `FML/Registries/minecraft:enchantments/ids`, `advancedrocketry:spacebreathing` to `128` to match with the AR config.
11. Start server

**Comment by OsirisKalev** [comment]
Ah, I see there was more to do than just changing the planet range. I only did a few changes (changed the planet range and changed the dimensions of Abyssalcraft and Twilight Forest to be lower than the range (31). #281

**Comment by ouroborus** [comment]
Now I've got a client crash from trying to enter space with a space station consisting of just launch pad blocks. My player was stuck in space, unable to log in. (This had worked in testing but I had used different blocks.) Using `/cofh tpx` from the console while the player was logging to teleport the player before the dimension loaded for the player in fixed this.

**Comment by ouroborus** [comment]
It seems that it's not possible to usefully get into space. Taking a rocket with satellite up gets you stuck at Y 1000. Relogging while in that state prevents you from being able to log back in.

**Comment by OsirisKalev** [comment]
I followed some of the things you've done, but I've done some things differently and I've had no problem with client crashes in entering space to the moon and Earth orbiting space station with rockets and with the space elevator, though this is only with an Earth orbiting space station.

What I've done is:

1. Deleted Adv. Rocketry folder to reset the worlds genned.
2. Done the same with you in regards to changing the biome ids to the 500 range and matched those to the planet biome definitions for blacklisting biomes and spawning biomes for high pressure and single biome worlds at the bottom of the file. However, I changed the dimension range to be from 31 onwards and left the space station dimension number alone.
3. I changed the Abyssalcraft dimensions and the Lost City dimension to 30, 29, 28, 27 and 26 respectively.
4. Deleted planetDefs.xml from the Advanced Rocketry config folder, because as I found out, if it doesn't exist (and normally it doesn't actually exist, this modpack has that in there, though who made it or whether it was just chucked in from a genned world, I don't know), it will gen a large set of random worlds for each world save that you do and properly uses the dimension range that you set.
5. Set the enchantment ids in the level.dat `FML/Registries/minecraft:enchantments/ids` to be switched around.

After starting both 2 singleplayer worlds and a multiplayer server and testing going to the moon and also creating a very basic space station on these instances, I have found 0 issues so far. I was worried on each attempt on leaving the planet after reading that you were getting stuck or just being unable to login that I would have the same issues.

The only difference we really have in regards to our configs is the dimension range we set and that I completely removed the planetDefs.xml file to let it generate it's own set of random worlds (though each instance always had a "Luna Moon" for Earth.

Beyond that though, I'm not sure. I am running the pack with simplified recipes mode (even though I feel like that config file should be the other way round and it should be called "Expert" and "Normal" modes, but that something else entirely), if that might change anything.

**Comment by ouroborus** [comment]
After the changes I outlined earlier, I removed the `config/planetDefs.xml` file and `world/advRocketry` directory, updated the config to `I:minDimension=-127` and `I:spaceStationId=-127`. Things seem to work now. I can get into space successfully and have quite a number of planets and moons. (The planets and moons except Earth and Luna all have generic names like "sol--100" and "sol--100:1". The stars have more appropriate names. I'm not sure if this is because the planets/moons are negative dimensions or if proper naming isn't implemented yet.)

**Comment by OrdinatorStouff** [comment]
As for 5.2 the major issues with Adv Rocketry should be resolved (existing worlds must delete planetDefs). AR content such as planets/stars/names/etc is still an ongoing WIP

**Comment by ouroborus** [comment]
@OrdinatorStouff There's still dimension collisions in 5.2 due to players having already allocated, via RFTools, at least some of the dimensions ATM3 has configured for AR worlds, especially DIMID 3, Luna.

**Comment by OrdinatorStouff** [comment]
Dim collisions should only be possible anymore with existing worlds that had created dims that AR expects to "own"

If there are still **non-dynamic** (i.e. rftools) dims without oxygen that aren't AR, please open a new ticket so we can tweak it in the AR config.
