### ISSUE TITLE
Crash involving Mekanism items on TiCon crafting table

### ISSUE THREAD

**Issue by Aeadon** [AllTheMods/ATM-3#295]
Crashed twice. Once I shift clicked a mekanism solar panel recipe and it crashed and the other time I placed the mekanism solar panel by itself onto the crafting table. 
[crash-2017-11-25_09.40.39-client.txt](https://github.com/AllTheMods/ATM-3/files/1503206/crash-2017-11-25_09.40.39-client.txt)
[crash-2017-11-25_10.46.04-client.txt](https://github.com/AllTheMods/ATM-3/files/1503207/crash-2017-11-25_10.46.04-client.txt)

**Comment by xhatz** [comment]
I have the exact same issue, even with not shift clicking... :(
Please help!

**Comment by OrdinatorStouff** [comment]
This is a very old, long-standing issue. Tinker and Mek devs have both tried to find out why it's happening and how to fix it but have not been able to.

I can't help other than to say 'do not put any block/item from Mek into any tinker's construct block that renders its contents in-game (Crafting Bench, Casting table/basin, Drying rack, etc)

If you need to temporarily log in to remove the items from the bench, change the Tinker's Construct config file to disable in-world rendering. It's clinet-only config and you could leave it off but it makes it so that NOTHING can be seen (including molten metals and part casts)
