### ISSUE TITLE
ATM-3 5.2

### ISSUE THREAD

**Issue by TheMrCaveman** [AllTheMods/ATM-3#303]
Server boots fine, but joining the server is never working!

15:39:44  [Info] Omuletus joined the game
15:39:44  [Info] Omuletus lost connection: Internal Exception: io.netty.handler.codec.EncoderException: String too big (was 39730 bytes encoded, max 32767)
15:39:44  [Info] Omuletus left the game

This happens to everyone joining the server.

I tried installing a new server instance, new world, fresh client install no luck!

So i reverted back to 4.5b and here everyone can join normaly. in the old and new world!

**Comment by OrdinatorStouff** [comment]
I remember dealing with the string too big issue back in ATM1 and I don't recall ever figuring out what was causing it or how to fix it. This might be a difficult one to track down

**Comment by Aphenon** [comment]
I had a similar issue on my server, and myself being the only one encountering the problem. i had to deop myself every time to log in. The problem fixed itself over time, so i do not have a concrete solution to the problem.

**Comment by OrdinatorStouff** [comment]
If this is still happening when trying to update to 5.6 or later, please re-open the issue. If so please provide all logs from the server, as well as a client that attempted to connect but couldn't so we can look through the specifics to try to find the cause.

**Comment by TigerWalts** [comment]
This is happening on every newly generated world with `5.7c`.

```
22.01 14:16:46 [Server] Netty Epoll Server IO #5/ERROR [FML]: NetworkDispatcher exception
22.01 14:16:46 [Server] INFO io.netty.handler.codec.EncoderException: String too big (was 38825 bytes encoded, max 32767)
22.01 14:16:46 [Server] INFO at net.minecraft.network.PacketBuffer.func_180714_a(PacketBuffer.java:400) ~[gy.class:?]
22.01 14:16:46 [Server] INFO at net.minecraft.network.PacketBuffer.func_179256_a(PacketBuffer.java:181) ~[gy.class:?]
22.01 14:16:46 [Server] INFO at net.minecraft.network.play.server.SPacketChat.func_148840_b(SourceFile:35) ~[in.class:?]
22.01 14:16:46 [Server] INFO at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:51) ~[ha.class:?]
22.01 14:16:46 [Server] INFO at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:12) ~[ha.class:?]
22.01 14:16:46 [Server] INFO at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[minecraft_server.1.12.2.jar:?]
...
```

It appears to be caused by the server sending a chat packet (`SPacketChat`) but the string is too big for Netty to encode. (This isn't to say that it's sending a chat message to the player, mods can apply a custom context to a message so that it doesn't get sent to the player's chat). It happens around the time the server is sending configs to the client. There's more to the stack trace but it doesn't reference anything but Netty.

I removed `AstralSorcery` from server and client as this appeared to be the last mod sending data before the error. This time I got the same error but the string length was different. `Mekanism` appeared to be the culprit this time, so I removed `Mekanism` and its dependants - Same error, again a different string size. This time no clue as to a possible mod causing it. This avenue of investigation is proving fruitless.

### But then...

On a whim, I reinstalled all mods and then renamed the `scripts` folder on both server and client. I was suddenly able to join.

I think one or more scripts might possibly be inflating the config data for some of the mods. When the mods try to send this config data to the client, it's too big for Netty to handle. I think you can ignore recipe changes in the scripts, I don't think they get sent, but if they do it's via a different method.

**Comment by Pelotrio** [comment]
Reopen this if its still a problem.
