### ISSUE TITLE
Embers Wildfire Core not craftable

### ISSUE THREAD

**Issue by Tejasminer** [AllTheMods/ATM-3#312]
The wildfire Core Recipe requires Embers Copper Plates and they are not craftable.
We are running the latest version of ATM3. 3 V 5.3

**Comment by ouroborus** [comment]
Maybe you can use one of the ore dictionary conversion devices to convert a variant of copper plate to the Embers version?

**Comment by Tejasminer** [comment]
The issue is that the recipe does not exist. I tried to use the industrial foregoing one and it did not.

**Comment by OrdinatorStouff** [comment]
I think this may be an issue of the "random chance" variation in Ember's Alchemy recipes that take some trial-and-error to get just right.

I think this because players have been able to craft the orb and ATM star even without reporting this as a blocker. 

Even still, a new update 5.7 will be coming out soon, if you feel this is still a legitimate issue comment or make a new issue and we'll investigate farther.

**Comment by nowifi4u** [comment]
You are still not able to do that. Altough there IS a method of creating those plates:
1. Obtain Uncrafting Table from @TwilightForest
2. Craft something with available Copper Plates (from @ThermalExpansion)
3. Uncraft that item, but use small arrows in the bottom left corner to select a recipe with @Embers Copper Plates
4. Use Ore Dictionary Exchanger from @IndustrialForegoing to exchange @ThermalExpansion Copper Plates into @Embers Copper Plates, provided you placed a previously made @Embers Copper Plate into "Examples" slot of the machine

**Comment by FallenEagle1** [comment]
@nowifi4u One last thing, what modpack version are you using? That is always important to know. Don't just say latest though, that doesn't mean much to me, as I've seen issues in that past where what looks like the latest is not, causing confusion.
