### ISSUE TITLE
Cant find the End Portal

### ISSUE THREAD

**Issue by Harbsbirdie** [AllTheMods/ATM-3#322]
My husband and I have been playing and today we tried looking for the end. We followed the eyes to where it says and there isnt anything there. We have dug around the area and still cant find it. Anyone else having this problem?

**Comment by TheKrister2** [comment]
As far as I have noticed it is a bug that has appeared since v5.3 was released. Don't know how to fix it at the moment though.

**Comment by Harbsbirdie** [comment]
Do you know how we can find the end at all?

**Comment by Jim209** [comment]
Depends on how "cheaty" you wanna be: http://chunkbase.com/apps/stronghold-finder will show you possible locations for strongholds.

**Comment by ouroborus** [comment]
Do they just not spawn at all or are the eye of ender just pointing to the wrong place?

**Comment by OrdinatorStouff** [comment]
Issuereports like this are hard to troubleshoot because the eyes of ender are somewhat hard to "follow" exactly and such. It also is not affecting all worlds as many servers/players have found strongholds and portal rooms in all pack versions so far.

I recommend going into spectator mode (gamemode 3) and then running /locate Stronghold to get coords of nearest stronghold, then /tp there and fly around through the ground (spectator mode is noclip) to see if the portal room is there.

Likely this is just a matter of inconvenient world spawn/generation.

Since this ticket is a bit aged already I'm going to close it but if the above steps do not work (/locate) on 5.6+ pack version, please create a new ticket and we can try to look into it farther.
