### ISSUE TITLE
Temporal bee from CareerBees

### ISSUE THREAD

**Issue by TheKrister2** [AllTheMods/ATM-3#324]
I know it is blacklisted, and that might be a good thing in and of itself. But at least on my private server I'd like to use it. Is it possible to undo the blacklist? I couldn't find it in any scripts or the like, or do I only need to re-download a fresh version of CareerBees.

I've played around with the Temporal bee and I have not experienced any errors, so long as it is used in moderation. Also, this might not exactly fit as something to post here, but I'm not sure where else to post it, so sorry if it's a tad annoying.

**Comment by OrdinatorStouff** [comment]
You are certainly free to change anything to your liking, we simply configure the modpack for what makes the most sense for balance and performance (the best we can anyway). This is why we created the "simplified" packmode too, since even though it's not our intended way for the pack to be played, we respected that many players wanted to play with "default" recipes.

At any rate, the temporal bee is blacklisted in the Forestry config `apiculture.cfg` -- just remove `careerbees.acceleration` from the blacklist section there and it should be breedable/obtainable again.

**Comment by OrdinatorStouff** [comment]
Also, this github is open to questions/feedback just as much as it is for bug reports. Share or ask whatever you'd like. We are also very active on our [Discord](https://discord.gg/FdFDVWb) if you wanted to visit and chat/ask questions or just hang out, as well.
