### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by GhostWalkerInc** [AllTheMods/ATM-3#334]
Im using server hosting service and im experiencing 90% to 100% cpu load all the time. Memory usage is only 3,5g of total 6g. I have reinstalled the server and then its great again but when i put in my old world it goes back to 100%. The original world is from v5.2. And now we use v5.5. If i remove all dimensions exept over world the cpu goes down to 40%-60% still high but playable.. I have only 5 players on my server. I can find anyone else having this problem so i dont know what to do now..

**Comment by OrdinatorStouff** [comment]
This is an extremely difficult issue to troubleshoot due to there being so many uncontrolled variables and circumstantial factors. The biggest clue though is the fact that it is fine in a new world but the old world has the performance issue.  
  
...while I'm at it let me ask this too: are you experiencing any **problems** in-game like lag or low TPS or something? The mere fact that RAM/CPU usage is at some level is purely anecdotal unless there's reason to believe it might be related to **symptoms** you're experiencing.

**Comment by GhostWalkerInc** [comment]
Yeah its very difficult to find an answer for this. I did some testing and i found out that when i make an new world and load chunks i get messages saying some mods has loaded an chunk and world gen server lag has increased. The mods i saw did this was Quark, Doomlike dungeons, binnie core and Roots 2. 

But also when i did some tests with my old world i found out that if i removed everything connected to minecolonies the server was using 40% less cpu.. 

What im doing right now is starting an new world and its now at 2% idle. And around 25% cpu with players on. I will monitor it and see if it goes back up to 100% it might have just been some corrupt chunks or blocks im my old world.. 

If i find something i will post it.. I really do love this modpack and i dont want to stop playing it..

**Comment by OrdinatorStouff** [comment]
It's always a good idea to keep an eye on server resources but you still didn't say if any players were experiencing any issues **in-game while playing** -- if there is no log, no stuttering, no crashes, then there is nothing wrong with Java using the computer resources that it has access to.  
  
Generating new chunks is always a performance hit, even in vanilla.

Feel free to open a new ticket if you continue to or start having in-game performance loss and we can try to troubleshoot the cause, otherwise it seems like there might not be need to worry in the first place.

Also if you didn't already know these resources here are some misc tools for monitoring your server you might enjoy looking into in your free time: Sampler (mod), TickProfiler (mod), BloodDebug (mod) and VisualVM (external program)
