### ISSUE TITLE
JEI highlight items in Inventorys doesn't work

### ISSUE THREAD

**Issue by Bircko** [AllTheMods/ATM-3#341]
in atm3 if i use search feature for inventorys it just highlight every inventory slot that isn't empty no matter what i search
![2017-12-22_21 13 27](https://user-images.githubusercontent.com/29576723/34311289-06a82f80-e75d-11e7-96a1-ee300c270bd3.png)

**Comment by OrdinatorStouff** [comment]
This is a bug in More Overlays that has been reported to that mod author 11 days ago but has received no response yet.

**Comment by Bircko** [comment]
what is the reason for this issue could i fix it by myself?

**Comment by OrdinatorStouff** [comment]
As far as we know there is nothing you can do nor anythign we can do at the modpack level to fix this, it's up to the MoreOverlays mod dev to look into a fix in the mod itsself: https://github.com/feldim2425/MoreOverlays/issues/41

Since it's already reported there and nothing we can do I'll close this issue out as it's not a "modpack" issue.

Thank you for reporting, hopefully the dev gets time to look into it soon.
