### ISSUE TITLE
Cant use Normal Minecraft Recipe

### ISSUE THREAD

**Issue by Ratte11** [AllTheMods/ATM-3#347]
Hello
I Cant craft the Normal Minecraft Recipe 
For Example : I want to craft a Cookie and i can only use the recipe from Pams HarvestCraft and not he recipe from minecraft

sry for my bad english 

Have a nice day

**Comment by masterX244** [comment]
did you switcxh packmode to simplified already? (its in config/packmode.cfg), the last line has to be changed from normal top simplified on client and server (if you are hosting a server and not playing in SSP)

**Comment by OrdinatorStouff** [comment]
I added a recipe for a single cookie that's the vanilla style of wheat+cocoa beans since that was specifically requested

**BUT**

With All The Mods that are in the pack, many recipes are customized by the mods themselves, not just by us for the pack. This is normal and intentional and we balance the pack around knowing that those changes are made. Pam's Harvestcraft changes many food recipes, so we configured most of pam's foods to restore more hunger/saturation than normal in return.
