### ISSUE TITLE
Extra Cells 2 wrong gas level emitter recipe

### ISSUE THREAD

**Issue by Erakol** [AllTheMods/ATM-3#363]
Hey there,

If I craft a ME gas level emitter for AE i get a ME fluid level emitter, wich works as a fluid emitter. In the inventory it is called gas level emitter if I place it on a glas cable it's called a fluid level emitter.

**Comment by OrdinatorStouff** [comment]
This will need some more research to find out what the issue is if any. I think ExtraCells stores mek gasses as "fluids" anyway (internal, from a code perspective) so it could be that a fluid emitter does the same thing functionally perhaps?

Sometimes AE2 components can be "toggled" into different modes by right clicking on them while holding a relevant object. Maybe try ricght clicking the emitter while holding a mek gas tank and see if that changes it at all?

Either way we'll look into it.

**Comment by Erakol** [comment]
I've tried it, but it doesn't work. I will report it to the extra cells devs. The strange thing is that it displays correctly in the inventory after the gas emitter is made, but in the emitter's GUI it is displayed as a fluid emitter.

If I have fourther information i share it here! Thanks for your fast respond.

**Comment by Boomflex** [comment]
Mod issue, not fixable on a pack level.

Issue raised with Dev.
