### ISSUE TITLE
Journeymap causing error on server startup

### ISSUE THREAD

**Issue by caledones** [AllTheMods/ATM-3#372]
Hey there, just downloaded ATM3 v5.7 server for the first time and on first run received this error. Haven't changed any configs or anything other than accepting the EULA.

Error log:
https://pastebin.com/n3W9pWN3

**Comment by Boomflex** [comment]
For future reference please use Pastebin or similar for crash logs.

**Comment by caledones** [comment]
My bad, edited it into a pastebin for you.

**Comment by diademos** [comment]
I have the same with my Server. 

et.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from JourneyMap (journeymap)
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.GameType.func_77142_a(Ljava/lang/String;)Lnet/minecraft/world/GameType;

When i delete the journeymap folder in the first folder the server loads again.

**Comment by Unnoen** [comment]
Journeymap 5.6.0b2 causes this, use 5.6.0b1 on the server side to fix the error. (There are no mismatch errors between those two versions)

**Comment by SpeedSlider** [comment]
Client side mods like journey map can be removed from the server files to prevent any potential mismatch issue and unintended errors or server bugs. Journey map bugs are a known issue with the latest releases of ATM-3 and many have found that reverting to release versions of Journey Map (e.g. 5.5.2) resolves many issues... However, players will likely lose waypoints when reverting back.

**Comment by Boomflex** [comment]
v5.8 will fix the Journemap issues.
