### ISSUE TITLE
Gendustry: uranium block not accepted by mutagen producer machine

### ISSUE THREAD

**Issue by ogradyjd** [AllTheMods/ATM-3#399]
**ATM** v5.7c;  **Genudustry Mod** v1.6.5.8-mc1.12.2

According to here:
https://bdew.net/gendustry/mutagen-producer/

...the uranium block (IC2) should produce 4.5 buckets of mutagen in the Mutagen Producer.  The problem is that the producer isn't accepting the uranium block.  You can't place a uranium block in the slot, and from what I see, ATM is creating the correct IC2 uranium block. The producer is accepting glowstone and redstone as it should.

I tried the U235 and U238 blocks (did you know just holding them can kill you?  I didn't until now), and those don't work either.    This may be a case of Gendustry just not having updated some table or something and the current uranium blocks aren't ore dictionaried right somehow by the mod.  

Not a high priority, but someone else may hit this because you gated a lot of higher tier stuff behind having to do forestry bees (what did we ever do to you to deserve that???  :)

**Comment by Complx** [comment]
The issue is that gendustry is not detecting IC2 as installed (see bdew/gendustry#259 ), for now we can create a config file to add in the recipes until bdew updates gendustry.

**Steps to fix:**
1. Open the modpack folder (for example, on the Twitch client, right click the modpack and click "Open Folder"
2. Open the `config` folder, then the `gendustry` folder
3. Make a new text file called `recipes.cfg` (make sure that it is a cfg file not a text file)
4. Open the file in notepad and copy the text below into it
5. Save the file and restart Minecraft
```
recipes {
    if HaveOD ingotUranium {
		mutagen: OD:ingotUranium => 1000 mb
	}
	
	if HaveOD blockUranium {
		mutagen: OD:blockUranium => 4500 mb    // U238 block
	}
	
	if HaveMod ic2 {
		mutagen: I:ic2:nuclear@1 => 9000 mb    // U235
		mutagen: I:ic2:nuclear@5 => 1000 mb    // U235 Small
		mutagen: I:ic2:nuclear@2 => 500 mb     // U238
    }
}
```
As for holding the uranium blocks, make a full IC2 Hazmat Suit set ([link](https://wiki.industrial-craft.net/index.php?title=Hazmat_Suit)) and you will not take radiation damage

**Comment by OrdinatorStouff** [comment]
Nice writeup @Complx  thank you -- we can take that approach into the modpack by default probably, saving the issue for anyone else in the future

**Comment by Boomflex** [comment]
Thank you @Complx for this fix.

This has been implemented in to the next update.

We will check the numbers for balancing at a future date.
