### ISSUE TITLE
[Suggestion] Add dank null

### ISSUE THREAD

**Issue by Optimoos** [AllTheMods/ATM-3#402]
Dank null has become one of my favourite mods recently. I looked around for a reason that it wasn't in All The Mods 3 but I couldn't find anything here or via Google. There are other nullifiers in the pack but they just don't compare to dank null in my opinion. Would it be possible to get this added?

**Comment by OrdinatorStouff** [comment]
I find the usefull nullifiers and their portable versions very handy. I would be interested in hearing your opinions about why you feel dank null is **signifigantly** better. Please use #1 the official suggestions issue for your feedback, however. I'm going to close this issue since our guidelines are to keep suggestions to that thread only, but am willing to hear further feedback there.
