### ISSUE TITLE
Journey Map compass and frame flickering / vanishing on minimap

### ISSUE THREAD

**Issue by Sinmiru** [AllTheMods/ATM-3#403]
Only started today, placed the flat lamps from Xtones in case that helps but not sure when exactly it started.

Also noticed (when looking at seemingly random recipes in JEI) that several missing texture squares will bounce around screen like the patreon icons in JEI. Not consistent with certain recipes, and doesn't do it very often.

**Comment by ogradyjd** [comment]
Don't quote me on this, because a quick search on the tubes turned up nada, but I think that's a random plug screen for minecraft developers.   If you click on the bouncing squares, you get links to twitter feeds or something.  I only tried it once, and of course I can't get it to pop up right now.  I know it's not tied to a given recipe because I've had it come up sporadically for just about anything.

**Comment by OrdinatorStouff** [comment]
These seem like odd cases that would be heard about more often if it was a common thing. Have you added or changed anything to the pack or is it exactly as is downloaded directly form curse or through the twitch app?  

Do you play on a server or single player? Have you seen anything like this before in other modpacks? What kind of computer / video card do you have?

**Comment by 5h5ong** [comment]
I have the same problem.

https://imgur.com/6oM9YZw

It started to disappear after using the kill command.
How can I fix it?

**Comment by SpeedSlider** [comment]
This issue will most likely be resolved by manually downgrading your Journey Map to version 5.5.2 which is the latest release version.

**Comment by Boomflex** [comment]
Fixed in v5.8
