### ISSUE TITLE
[5.7c] Server crash while play, then the server hangs in a start up loop

### ISSUE THREAD

**Issue by Terminator81** [AllTheMods/ATM-3#415]
can someone take a look 
[crash-2018-02-13_08.33.27-server.txt](https://github.com/AllTheMods/ATM-3/files/1719041/crash-2018-02-13_08.33.27-server.txt)

how can i prevent the server from crashing?

**Comment by Boomflex** [comment]
Can you please post the crashlog to Pastebin as I don't want to download files from people I don't know.

Thanks.

**Comment by Boomflex** [comment]
It looks like that there is an issue with someones Refined Storage system.

I would recommend making a quick change to the forge.cfg to read:

Line 52 # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

Line 55 # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true
