### ISSUE TITLE
Tome of Alkahestry needs balance

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-3#440]
By default the tome is OP in regards to being able to dupe diamonds and nether stars and steel and other things by using only redstone as input. To quote DW20: "The cheaty book of cheatiness" 

Most packs just disable the book outright which is an option BUT the recipes and charge is supposed to be modifyable per the mod's wiki but the methods to do so are not clear (it's not a category in the reliquary config).

Opened issue for more details on how to customize: https://github.com/P3pp3rF1y/Reliquary/issues/302

**Comment by OrdinatorStouff** [comment]
Maybe it can retain default functionality and need a difficult crafting recipe instead such as using the Anima Mundi or Orb of Transcendence as an ingredient

**Comment by ogradyjd** [comment]
I'd second the difficult recipe.  It would have to be balanced with Mystical Agriculture - which can give you all the things that the book can, but easier.  It's a pain to use the book, but easy to use MA seeds with Greenhouse Glass above.  Balance to taste.

**Comment by SpeedSlider** [comment]
Perhaps, there is a way to dictate what kind of input is required to dupe certain items or just increase the dupe cost to eliminate its use on low level stuff. Examples would be to require emeralds for gem duping instead of redstone, and some ingot for ingot duping, etc. If that is too difficult then just increase the cost to nether stars to dupe anything and then it would only be used to dupe expensive items... etc.

**Comment by OrdinatorStouff** [comment]
closed by https://github.com/AllTheMods/ATM-3/commit/d5c0585042d4c63aeeb746daa3e942c90c811a02

**Comment by Willy347** [comment]
![image](https://user-images.githubusercontent.com/29513092/41070342-97eada5c-69f2-11e8-8a3b-b946ed822017.png)
