### ISSUE TITLE
Steam fluid compatability

### ISSUE THREAD

**Issue by FallenEagle1** [AllTheMods/ATM-3#487]
This is something I personally have not tested, but this was brought up in the discord

> i do not know if this is the right place but here goes.
on atm3 
       version 5.9.2
      minecraft version 1.12.2
there are three different steam fluids, from Nuclearcraft,  Advanced generators and Industrialcraft.
there is no oredictionary compatability between those three and there is no fluid oredictionary converter 

Not sure if much can be done to get fluids to be compatible with each other but for steam this sounds like a good thing to have the same across the board.

**Comment by OrdinatorStouff** [comment]
This is something I wish was handled better as well. The problem is the fluid registry is very barebones nad not all that configurable. 

if any mod registers a flu_d called "steam" then as soon as another mod also tried to regiester "steam" forge say 'nah we got one of them already' and the same one "steam" is used.

This problem happens when ic2 decides it's going to register "ic2_steam" and "ic2_superheated_steam" and nuclearcraft is wanting to register "steam_liquid" and another mod maybe wants "gaseous_water" (for examples)

The thing your requesting actually happens automatically BUT only if all mods use the same name. Steam is a great example of how much variation there is of naming conventions and afaik unless Forge revamps the fluid registry and makes it more extensible I don't think there's a whole lot that can be done about this

The only idea I've ever been able to come up with is adding a modpack recipe to somehow convert one mod's steam (or whatever) to another kind, but that doesn't "FIX" the problem still

**Comment by leftyde** [comment]
the weird thing is, I need to relog(not restart MC!) so TE can be used with steam, on my first login, TE Steam doesnt work.

but honestly, why in the world does this happen? If Forge sees, there is steam already loaded, why not fucking skip this next registration with an, it's already there, done. so like skip and its ok.

**Comment by Boomflex** [comment]
@leftyde I edited your comment to remove the unnecessary language used.

**Comment by kevincook** [comment]
Is this related?  https://github.com/aidancbrady/Mekanism/issues/4997

**Comment by Boomflex** [comment]
Thermal Expansion causing issues. KL seems to be on top of it.

Will close for now.
