### ISSUE TITLE
No end dragon in latest beta atm v5.9.3

### ISSUE THREAD

**Issue by xdarksagex** [AllTheMods/ATM-3#505]
Using latest beta and i went into end and there was no dragon or portal. All the towers were there, even flew around and eventually spawned a dragon in with command /summon and still didnt get a portal after killing it. Not sure if there is something im missing as i watched a video of someone playing atm3 and he just took portal and dragon was there with portal made out of bedrock blocks already there, where its not for me. Playing single player

Also feel like there are waaaay to many abyssal craft zombies spawning, like they almost out number the enderman in the end.

**Comment by Boomflex** [comment]
This has been a bug since vanilla and unfortunately something seems to have brought it back again.

I tested 6 new worlds and it happened 1 time. The fix for this is to leave the End via /spawn then to delete the DIM1 folder from the relevant save file and then go back through the End Portal. This will regenerate the End and hopefully include a Dragon.
