### ISSUE TITLE
Minecraft saying I need to download the latest java version? Should I download version 10?

### ISSUE THREAD

**Issue by Saad1950** [AllTheMods/ATM-3#570]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by FallenEagle1** [comment]
No. Minecraft doesn't play very well with java 9 or 10, so use latest java 8. I believe that is 1.8.0_171. Other thing to do with updating is to go in twitch and change the launcher used from native to jar. The native launcher has a habit of using the version of java it is packaged with (1.8.0_25). While changing that, make sure twitch is seeing java 1.8.0_171 **64 Bit**. If 64 bit is not seen, you might need to double check that the correct java was installed. Easiest way to do that is go to the all downloads section on the java website and select 64 bit offline.

**Comment by Saad1950** [comment]
Thanks man but one more thing, my computer is a 32 bit computer. Also if I only used one mod at a time it works but the whole mod pack it doesn’t.

**Comment by Buuz135** [comment]
You can't play big modded packs with 32 bit java/computer

**Comment by FallenEagle1** [comment]
This modpack takes a decent amount of ram to run. Minimum seems to be around 5 Gb, but 6 seems to be a decent amount to work with. 32 bit java can only allocate up to 2 Gb max. So thats where the issue would be.

**Comment by Saad1950** [comment]
So basically my computer is crap
Anyways, what is the maximum number of mods I can play on minecraft if I have a 32 bit computer with 4 ram?

**Comment by Blueletric** [comment]
50?

**Comment by Blueletric** [comment]
Maybe less, 32 bit can’t handle much.

**Comment by FallenEagle1** [comment]
Something that only takes probably 2Gb to run, since the other 2 will be needed to run the rest of the computer. That number will fluctuate a little, but that's what I've always heard for a baseline. But basically modpacks that are essentially vanilla with only a couple mods, such as maybe Nature's Beauty (not sure on how much that one needs to run). Minecraft 1.10 and up changed how the game runs, and it takes more ram because of it, so it limits what older computers are able to run unfortunately.

**Comment by Blueletric** [comment]
You might be able to play some 1.7.10 packs

**Comment by Saad1950** [comment]
You have any examples?

**Comment by Saad1950** [comment]
Nvm
