### ISSUE TITLE
Mining Issue

### ISSUE THREAD

**Issue by PR3DHUNT3R** [AllTheMods/ATM-3#579]
## Expected Behavior
I should be able to mine without issues

## Current Behavior
while i am mining i encounter an issue/bug that makes the screen shake (Overworld, Nether & Mining World) I cant do anything other than quite and reload into the Server, sometimes i have to reload the modpack. 

It doesnt happen instantly but it happens everytime i go to mine. Not sure if its me or something else.

**Comment by Boomflex** [comment]
Non-reproducible issue.

Uninstall pack and reinstall it.

**Comment by SouLacrity** [comment]
I was having the same issue and since it was closed i decided to try and find the issue. I believe i have found the issue. I was able to reproduce it several times in different situations.

The item Automatic Torch seems to be causing the bug when mining. Sometimes when it places a torch automatically the screen either shakes or freezes, and only logging out will get you out of it. At that point when you log back in there is a death marker from the map waypoints even tho you didnt die.

It might be some interaction between the two mods, but either way I believe if you dont have the item Automatic Torch in your inventory you should be fine. Tho I really like the item so I hope the issue is fixed eventually.
