### ISSUE TITLE
Server crash due to ae2 alpha

### ISSUE THREAD

**Issue by PhanaticD** [AllTheMods/ATM-3#647]
as reported here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3578

they will not fix it, and I cannot start my server, so what do

**Comment by GuntherDW** [comment]
This crash is not due to AE2, but ExtraCells being outdated.

As explained to you in the bug report AE2 rv6 is far from release quality just yet. The first alpha build only just landed, and as usual it is to be expected to break compat because it's an alpha.

So revert back to rv5-stable-11 or remove AE2 addons.

**Comment by Yoosk** [comment]
It's quite weird that alpha works fine on our official servers, and on test servers

**Comment by GuntherDW** [comment]
He's using cells from ExtraCells in storage, and some of the method descriptors regarding inserting into cells have changed to support fluids natively.

This is what's causing the crashes.

**Comment by fscan** [comment]
FYI, a rv version change in AE2 means we plan to do changes that affect the API until it hits BETA.

**Comment by PhanaticD** [comment]
it errors on pretty much every import bus thats not really a good option for me

**Comment by HeroOfFire45** [comment]
Reverted, reccomend closing

**Comment by FallenEagle1** [comment]
Hotfix is out, 5.9.8c. This reverts ae2 back.
