### ISSUE TITLE
Infinity storage - Energy storage (DE)

### ISSUE THREAD

**Issue by MythixDino** [AllTheMods/ATM-3#683]
Firstly I'm not sure if this is intended or not, but they can both store an 'infinite' amount of energy.
But the price of these are very different, I would even say the infinity storage is unbalanced because of it's cost compared what you'd need to make a DE T7 energy storage.
And then the size. Infinity storage is just one block, while the DE storage is far bigger.

**Comment by DKnightADRI** [comment]
I do agree with this.

I kind of rushed the Overloaded infinity capacitor and got it pretty quickly, did not even need an energy storage before that (except a Mekanism energy cube). Wither farm and done.

My solution would be: make the recipe of the infinity capacitor harder (in a way it could be seen as an 'upgrade' of the max tier DE multiblock) while making the DE energy storage cheaper (energy core and particle generators) so the lower tiers are accessible in the mid-game as well. Right now I dare to say there's not a single player who's ever build the first 4 Tiers of the multiblock because even the lowest tiers require quite some awakened draconium (which used to fine, but not anymore in this DE version).

**Comment by Yoosk** [comment]
Excuse me? On what pack-mode are you playing? Because on default one it requires atm star and that's certainly not cheap.

**Comment by DKnightADRI** [comment]
I played it on default (meaning I did not change any configs), latest patch, it did not require an atmstar, just nether stars and some other resources, but I could double check if you want me to.

**Comment by Yoosk** [comment]
Maybe something borked then, cause in my test instance requires tweaked items.
