### ISSUE TITLE
Game crashes while loading

### ISSUE THREAD

**Issue by skateereer** [AllTheMods/ATM-3#695]
Hello, I installed all the mods 3 today and while loading it up for the first time, the launcher froze. It would not respond, and I had to force quit. No crash log appeared, but I have attached the game output log.

## Expected Behavior
The game should load into the menu screen.

## Current Behavior
Loading screen froze until I force quit out. 

## Steps to Reproduce

1. Launch game
2.
3.
4.

## Detailed Description

[latest.log](https://github.com/AllTheMods/ATM-3/files/2242817/latest.log)

**Comment by FallenEagle1** [comment]
Usually when it crashes and does not produce a crash log, it seems to be related to the ram settings. Not always, but that seems to be somewhat common. You're java is up to date, and have about 5.5 Gb allocated. How much does your computer have total?

**Comment by MiunaOshino** [comment]
Yeah I don't believe you can play this pack on a computer that has 8GB RAM. I tried with my laptop, i either crashed during loading or froze on the main menu.

Check out [ATM 3 Lite](https://minecraft.curseforge.com/projects/atm-3-lite) though, works fine on my laptop.

**Comment by daogarualexx** [comment]
With 8 gig of ram on computer you cannot load anything from version 5.x and up but you can try lite or an older version. I played with 6 gig for atm in the past on a laptop and I was able to get it running but not very good with at least 8 gig to the atm I should be able to run it but more is better until java says nope.(even with over 8 gig of ram into the atm its not guaranteed to work decent because it can get CPU and GPU hungry sometimes and at least 1 hour of gameplay until restarting the game to limit memory leaks and having smooth performance.)

**Comment by skateereer** [comment]
That’s unfortunate :( I didn’t know there was an ATM 3 Lite though so I will check that out. Thanks for the help!

**Comment by FallenEagle1** [comment]
You can get a computer with 8 Gb total to work with ATM3, it just takes some tweaking to make sure things load and run somewhat smoothly. But yes, there is a lite version of the pack that doesn't have some of the larger mods that make the normal pack much bigger.
