### ISSUE TITLE
Different mod resource blocks don't show up in JEI or creative inventory

### ISSUE THREAD

**Issue by Sparks5** [AllTheMods/ATM-3#696]
## Expected Behavior
Searching for 'tin block' in either JEI or the creative inventory should yield results for about 10 blocks of tin from different mods, and the same applies to other resource blocks.

## Current Behavior
Only the resource block from Thermal Expansion shows in the creative inventory or JEI despite the other blocks definitely still existing

## Steps to Reproduce
1. Search for a resource block in JEI or creative inventory
2. Confirm that the only resource block that shows up is from thermal expansion
3. Put a TE resource block into a diamond chisel to confirm that the other resource blocks do exist

## Detailed Description
Searching for the resource block should return all the different resource blocks from all different mods.
The same issue exists for TConstruct tool forges and other Tinkers tool building blocks (part builder etc)

**Comment by FallenEagle1** [comment]
This is working as intended. All of the duplicate blocks (10 types of tin, etc) were consolidated down so that everything uses only one version of each. The others are still able to be gotten (chisel) which is nice if you like the texture, but having one for crafting/automation is much better in a number of ways than having 10+
