### ISSUE TITLE
Yellorium Blocks

### ISSUE THREAD

**Issue by jeffwcollins** [AllTheMods/ATM-3#74]
Can you add yellorium blocks to chisel, as it conflicts with uranium blocks.

**Comment by OrdinatorStouff** [comment]
TODO: Extreme reactors config option to add yellorium to uranium oredict. Manually include it as well in crafttweaker scripts.

**Comment by OrdinatorStouff** [comment]
Update: this is indefinitely on-hold: Oredict changes have been made BUT chisel variants must be added manually (oredict is not "automatic" for chisel inclusion anymore) but ModTweaker does not yet have chisel support added back in for 1.12 MC version.

Closing ticket for now since there's nothing we can do about it for now.
