### ISSUE TITLE
[Suggestion] Some creative items don't have recipes!

### ISSUE THREAD

**Issue by ReiDaTecnologia** [AllTheMods/ATM-3#755]
Various creatives items should have recipes using (obvious) the ATM Star, for exemple "Creative Exchanger".

## Current Behavior

Various useful items don't have recipes like "creative exchanger"

## Possible Solution
Give me the permission to do a PR with the creative items with recipes.

## Steps to Reproduce

1. Search in the jei "Creative" and should show various creative items.
2. Check with JEI if they actually have recipes
3. Some will have some not.

## Detailed Description
List of the creative items without recipes:
Creative Exchanger
Creative WireLess Crafting Terminal
Creative Conversion Kit
Creative Compressor
Creative BookCase
**Thermal Series Creative Items:**
FluxBore
FluxSaw
FluxoMagnet
HypoInfuser
Alchemical Quiver

**Comment by FallenEagle1** [comment]
Looking at remix, since that is the pack moving forward.
Items that won't be added:
Creative exchanger - allows for duplication of blocks, not a good idea.
Creative conversion kit - can allow certain machines for duplication stuff.
HypoInfuser - Infinite liquids.
Alchemical Quiver - Infinite liquids.

I am looking at adding some things those.
