### ISSUE TITLE
Thaumcraft Quartz Sliver Recipe Broken in 3.5.10.1

### ISSUE THREAD

**Issue by ShaneCourtrille** [AllTheMods/ATM-3#768]
The recipe for Quartz slivers was broken in the 5.10.  I was able to make them fine in 5.9 and the recipe shows up fine in JEI but it just doesn't work.

**Comment by Yoosk** [comment]
Have you tried updating to 5.10.1? There was issue regarding crafting recipes

**Comment by ShaneCourtrille** [comment]
Sorry, should have been more explicit as we're running 3.5.10.1 already.

**Comment by FallenEagle1** [comment]
![image](https://user-images.githubusercontent.com/22630113/45601754-36967900-b9cf-11e8-84e7-205f2532007d.png)
 It is working for me. Have you changed anything? Or, have you double checked that it is 5.10.1? I think someone mentioned an issue from twitch that it still gave them 5.10.0 for some reason. I think that issue is taken care of, but something to check.

**Comment by ShaneCourtrille** [comment]
I double checked and it's still 5.10.0 even though Twitch is showing 5.10.1.  Going to downgrade/upgrade and see if that resolves it.

**Comment by ShaneCourtrille** [comment]
Resolved by downgrading/upgrading and upgrading server
