### ISSUE TITLE
[5.10.1] All The Mods, Immersive Engineering Graphical Bug

### ISSUE THREAD

**Issue by AssaultEngineer** [AllTheMods/ATM-3#786]
so I am playing on a server and I decided to build a steam power set up from immersive engineering
but when I built the multiblocks for the alternator it looked ok for a moment then proceeded to look 
like this

![image](https://user-images.githubusercontent.com/44123131/46909002-4dea5880-cee0-11e8-9261-bd448082bc9d.png)
im not sure how to fix or what causes it they are all in the same chunk as you can see
and relogging doesn't fix it

**Comment by AssaultEngineer** [comment]
![unknown](https://user-images.githubusercontent.com/44123131/46910789-d4faf900-ceff-11e8-825c-b9d06da3349d.png)
it also occurs with the steam tubine

**Comment by AssaultEngineer** [comment]
ive discovered that moving the structures to a different chunk fixes the problem but I still don't know what caused it

**Comment by SpeedSlider** [comment]
Closed due to inactivity. This issue would be easier to troubleshoot using our discord channels. A lot of issues can be addressed in our Frequently Asked Channel. If those do not help then our Help Desk channel works well since the issue can be addressed in real time based upon player/helper/staff availability.
