### ISSUE TITLE
Exception caught by Thaumcraft

### ISSUE THREAD

**Issue by Dovencio** [AllTheMods/ATM-3#787]
## Expected Behavior

Load the game properly 

## Current Behavior

Game crashes during startup

## Steps to Reproduce

1. Startup game

## Log

https://gist.github.com/Dovencio/5317aa3854654a9e779846798f22af2a

## Detailed Description

Computer info:

i-7
8Gb ram
NVIDIA GPU 940 MX 1GB

**Comment by FallenEagle1** [comment]
This is caused by using too new of a forge version. I'm assuming from some of the other details in the report that this is on the twitch launcher. Twitch for some reason has a habit of putting too new of a version of forge with the modpack. The one that it is trying to use is forge version 2770. The correct version that the modpack is shipped with currently is 2760. Change this in the profile options of the modpack. 

While doing this, to help with performance of the pack and to fix other potential bugs, I would go through this link and follow the changes it suggests.
https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/

**Comment by Dovencio** [comment]
It worked thanks
