### ISSUE TITLE
Missing ore in void ore miner recipes

### ISSUE THREAD

**Issue by SubjectHawk66** [AllTheMods/ATM-3#810]
I've noticed rutile ore is not available for infinite mining

## Expected Behavior
It should probably be mine-able as it is crucial for tech reborn automation and is quite hard to get from other sources.

## Current Behavior
Rutile ore is not mine-able by void ore miners.

## Possible Solution
Adding rutile ore to the configs in environmental tech. I suggest a quite high rarity as it is almost 4 times as rare as iron.

**Comment by SpeedSlider** [comment]
There are other options for obtaining this ore. JEI identifies the various dims that the ore can be found in including the ore gen precentages. A digital miner can then be used to obtain the ore. For infinite generation the output, titanium, can be used to craft mystical agriculture seeds to produce an infinite amount. ATM3 is in steady-state and this issue is considered an enhancement since other options are available. Closing issue.

**Comment by SpeedSlider** [comment]
Work around options provided due to inactivity this issue is being closed.
