### ISSUE TITLE
Server Crashing on startup

### ISSUE THREAD

**Issue by RyRy1986** [AllTheMods/ATM-3#814]
## Expected Behavior

server start

## Current Behavior

crashes 

## Log

https://github.com/RyRy1986/crash-report/issues/1

**Comment by FallenEagle1** [comment]
```net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Advanced Generators (advgenerators)
Caused by: java.lang.NoClassDefFoundError: net/bdew/generators/sensor/Sensors$$anonfun$10```
Usually when a NoClassDefFoundError pops up it usually means there is something missing. How did you set up the server? Where did you get the serverfiles from? Is this hosted or on your own computer? If you try starting it up again, does this still occur? There are some questions here that would help determine what might be wrong. Also, while its not as old as it could be, the java version is older, that it might be worth updating it if you can. The version being used is 1.8.0_101, while the newest java 8 is 1.8.0_191.

**Comment by RyRy1986** [comment]
I got the server fills form [curseforge](https://minecraft.curseforge.com/projects/all-the-mods-3/files/2639207#additional-files) I got the full one. I'm using Multicraft to host it, and yes every time I try to start it says that all the time. before I installed it on my server I started it on my computer and it started ok, is there anything else you need to know I will tell you everything I can.

**Comment by kaiokenmaster** [comment]
I'm having a similar problem. When I use the "ServerStart.bat" it opens the command terminal then gives me a warning saying there was an error and it could not download forge.

**Comment by Yoosk** [comment]
Forge is bundled with server pack files, that error can't really show in latest versions

**Comment by kaiokenmaster** [comment]
Is this not the latest version?
[https://minecraft.curseforge.com/projects/all-the-mods-3/files/2521709](url)
I checked out the others items in the file tab and I get like 2.9 MB zip folders that have a folder a manifest and a link to the mod list. How do I start a server with this because from what I can tell this is the latest update I can find?
Can you link me to the correct sight to download the server files because I'm having trouble?

**Comment by FallenEagle1** [comment]
That is not the latest files by a long shot. That is version 5.7c, and latest is 5.12.0 which is the 24th update since then. If you are using technic as your client launcher, I would suggest switching over to either twitch or multimc

https://minecraft.curseforge.com/projects/all-the-mods-3/files for all of the different versions, specifically https://minecraft.curseforge.com/projects/all-the-mods-3/files/2681456 this one for the 5.12.0 server files.

**Comment by kaiokenmaster** [comment]
Thanks the server is working smoothly now. I'm probably just not used to it but I could not find that page for the "Full release" version of the mods in the files tab. Possibly consider making links on the main page to also advertise raw files instead of just the 20% discounted server that you need to buy. But that's just me. anyways thanks again.

**Comment by FallenEagle1** [comment]
https://minecraft.curseforge.com/projects/all-the-mods-3/ This is the main page for the modpack, I don't know why any others would show different. Also, clicking the picture of the modpack in question will take you to that page linked above, or the corresponding pack in question. In any case, glad you got it sorted out.
