### ISSUE TITLE
Wyvern Chest piece requiring Angel Ring

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM-3#818]
Should be used for the Draconic Armor as it is in Remix.

**Comment by FallenEagle1** [comment]
It's been fixed in remix, and most changes that are related like this, most are going to be put into remix. Atm3 is more of legacy at this point and is just going to be getting mod updates as time goes by. More of what is needed is to have remix show up in twitch before atm3 (legacy) and a description needs to be put in atm3 pointing to remix.
