### ISSUE TITLE
[5.11.2] Crash after 30 - 60 minutes of gameplay

### ISSUE THREAD

**Issue by Stannks** [AllTheMods/ATM-3#820]
## System Details
Windows 8.1
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

## Expected Behavior

For my game not to crash.

## Current Behavior

I join a server, play for around 30 minutes to an hour. Then bang!
Client stops responding, my mates on the server tell me I disconnected.
Then I forcibly close the game and launch it again.

## Possible Solution

I guess memory allocation is a possibility but I kind of doubt it.
Unless allocating too closely to the capacity of my computer's memory
is a thing? I give it 9GB out of a possible 16GB. And whilst running
my computer still has on average ~1.3 - 2GB available when I'm playing.

## Steps to Reproduce

1. Launch game.
2. Join server.
3. Wait 30 minutes to an hour.
4. Force quit the game due to it not responding.
For the 3 times it has crashed, nothing I can think of is distinguishable
that seems to trigger it each time.

## Log

https://gist.github.com/Stannks/0dc31a0aeca59bf1cc19cfb2c5f30654

**Comment by Yamza** [comment]
To start off, an old java version is being used due to having "native launcher" selected in your settings. Go through this post and make the changes https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/.

Were any changes made to the pack? This is the thing causing your issue but it doesn't seem familiar.
`at com.blamejared.slimyboyos.network.MessageEntitySync.handle(MessageEntitySync.java:50) ~[MessageEntitySync.class:?]`

Perhaps that is the name of the server you've connected with. The error starts appearing around the time Minecolonies stuff starts showing up in chat, so it's possible the error is connected to that.

**Comment by Yamza** [comment]
Apparently Slimy Boyos is a mod included in the pack which allows slimes to pick up items. I would have to guess then that a slime may have picked up an item that isn't rendering correctly. I would have someone who is OP on the server try `/cofh killall` and then `/cofh killall item`.
