### ISSUE TITLE
Inventory Freezing

### ISSUE THREAD

**Issue by SinisterandSly** [AllTheMods/ATM-3#834]
Hi,

Whenever I open any inventory I experience freezing for 1 to 5 seconds. This occurs consistently despite having reinstalled the mod pack several times. I read that it may possibly be something to do with a recipe book but I'm uncertain. My PC is more than capable of running the mod pack and I have followed the recommended launch settings for Twitch too.

Any help would be greatly appreciated, cheers.

**Comment by SpeedSlider** [comment]
There is not enough information provided in this issue to help. This issue is best addressed by using our Frequently Asked Questions and Help Desk channels in discord. A couple of recommendation would be to ensure that sufficentt RAM is allocated in Twitch (typical 6 Gig unless you only have 8 Gig total available); another issue could be your java version that may be 1.8.0.51 which is the default packaged with twitch. If that is the case then update to the latest 1.8 version of Java. Do not use Java 1.9 as there are issues with it and modpacks at this time.

**Comment by SpeedSlider** [comment]
Issue closed due to not enough information. Basic troubleshooting steps provided and recommended discord for future followup.
