### ISSUE TITLE
Unable to start a server due to crash on start

### ISSUE THREAD

**Issue by SirGayy** [AllTheMods/ATM-3#839]
Server stops as soon as it starts, i don't have much experience with crash logs so bare with me, main thing of note was this line in the crash log:

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTB Utilities (ftbutilities)

If it'll help i can post the entire crash log in here, i bought a server about three days ago and have been trying to set it up but this kept happening, any kind of help is appriciated.

Full crash logs: https://gist.github.com/SirGayy/b0bc7e6aae37015c3dc9ed9df40d27ec

**Comment by FallenEagle1** [comment]
The issue is java 9 trying to be used, when java 8 has to be used. The java it says it is using is `Java Version: 1.8.0_192, Eclipse OpenJ9` that openJ9 is the issue. In the server settings panel, there should be a java select dropdown, and on of the options is legacy. Select that and restart, you should be good then.

**Comment by SirGayy** [comment]
Worked like a charm, thank you.
