### ISSUE TITLE
Not able to connect to server ruunning on debian lunux

### ISSUE THREAD

**Issue by MechanID** [AllTheMods/ATM-3#840]
## Expected Behavior
Successful connect to server

## Current Behavior
not able to join server

## Steps to Reproduce
1. Start server on  debian linux
2. try to connect
3. get an error

## Log
https://gist.github.com/MechanID/c53a049e101334d91fdf55c64b9b5a33

## Detailed Description
OS details:
~ cat /etc/debian_version
8.11
~ uname -a
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux
~ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

Server on my windows desktop works fine, so maybe issue not related to game server, but to some software configs (java or something else) on my linux VPS, any help appreciated.

**Comment by Yamza** [comment]
Assuming you've never actually connected to this world before. Try deleting the world provided so a new one can be generated. Seen this happen before from a newly generated world.

The issue is this `String too big (was 40068 bytes encoded, max 32767)` Which _typically_ means that something in the world, or something in your inventory has too much data. So if my previous assumption is incorrect then this is the actual issue. 

You would need to either have someone find and replace the offending block in world, or have your player data wiped depending on the situation.

**Comment by MechanID** [comment]
Thanks for your reply!
i deleted world folder two times and restarted server after each try - same issue, i also uploaded "world" folder from server that work fine on my windows desktop PC - same issue, so looks like this is not world map related issue.

**Comment by FallenEagle1** [comment]
Might try and see if this is still an issue with modpack and serverstart scripts being updated now if you are still inclined.
