### ISSUE TITLE
Crash on sand block

### ISSUE THREAD

**Issue by rgreene** [AllTheMods/ATM-3#863]
## Expected Behavior

not crash

## Current Behavior

crash

## Possible Solution

fix issue caused by interaction (digging/standing) on sand block

## Steps to Reproduce

1.  Login
2. Walk to sand blocks
3. Stand on sand blocks for a moment and client freezes
4.

## Log

Log shows nothing....just stops.

**Comment by Yamza** [comment]
Log might show something though..

**Comment by rgreene** [comment]
I'll try again. I had nothing when I checked. I'll do server and client
captures.

**Comment by rgreene** [comment]
If it helps, happens with sky factory 4

**Comment by FallenEagle1** [comment]
That last comment didn't give any information. Was it supposed to be a link to something or...?

**Comment by rgreene** [comment]
Logs:
[client_logs.zip](https://github.com/AllTheMods/ATM-3/files/3129633/client_logs.zip)
[Uploading server_logs.zip…]()

**Comment by rgreene** [comment]
In the comment above, I have included latest and debug logs from both server and client.

**Comment by FallenEagle1** [comment]
Couple things here. First one, that server logs isn't a file, its just a link back to this website page for the issue. Second, for future reference it would probably work better for putting the logs on gist.github.com instead, so that anyone looking doesn't have to download the files to see if its related to what they are looking for (or for fixing the issue). Last, there doesn't look to be anything in that client file. All it looks to be is the client logs for the latest startup, which doesn't appear to have any issues. It doesn't appear that a singleplayer world or multiplayer world was even joined, just a launch of the game to the main menu. The logs would have to be of when the crash happens. For that matter, a crash report should be saved as well when a crash happens. It would be in the crash report folder, not in the logs folder.

**Comment by rgreene** [comment]
The client freezes would be more appropriate but never recovers.

**Comment by rgreene** [comment]
server log does show client connected: rockin4106

**Comment by FallenEagle1** [comment]
Now that the server files are there, looking through it, nothing shows an issue. Have you tried a new world to see if it is world specific? Or tested in singleplayer to see if this still occurs?

**Comment by rgreene** [comment]
I have tried single player, prior version of client and server, new worlds so far.

**Comment by FallenEagle1** [comment]
Odd, as no one else has had issues at all

**Comment by rgreene** [comment]
I searched for this issue prior to posting.  I've no clue as to why only sand blocks....just step on one and wait a few seconds or dig up a few and then freezes.

**Comment by FallenEagle1** [comment]
I get that. But we've had people test it today already, and the modpack version has been out for a little bit now and this is the first of something being pointed out of this nature, so it leads me to believe it is something with your setup, although I don't know what might be the cause here.

**Comment by rgreene** [comment]
I've installed multiple times with GDLauncher and on Twitch.  I agree. with the oddity.

**Comment by rgreene** [comment]
not sure how, but tried Twitch again and it works.  The issue must lie with GDLauncher now.
